# Generated by Django 5.1.5 on 2025-02-04 15:11

import Gestion.validadores
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleados',
            options={'verbose_name': 'Empleado xx', 'verbose_name_plural': 'Empleados yy'},
        ),
        migrations.AddField(
            model_name='empleados',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleados',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='apellido  dd'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='cargo',
            field=models.CharField(choices=[('Gerente', 'Gerente'), ('Vendedor', 'Vendedor'), ('Cajero', 'Cajero')], max_length=50),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='cedula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10), Gestion.validadores.validacion_numeros]),
        ),
    ]
